### ISSUE TITLE
表单校验失败

### ISSUE THREAD

**Issue by zhiyiYo** [GCS-ZHN/AutoCard#30]
## Bug Description
这几天打卡总是失败，日志里面说：
```
[***0***101*** 0***:06:***4] [main] ERROR top.gcszhn.autocard.service.AutoCardService - 表单校验失败，请检查健康打卡页面是否更新或等待一会再次尝试，若更新请删除缓存文件并重启打卡程序
```
修改了 `AUTOCARD_CACHE_FLAG` 的值之后还是报错

**Comment by GCS-ZHN** [comment]
如果是本地程序，请直接删除autocard_cache.json后重启程序。如果是github action，参数名是AUTOCARD_CACHE_FLAG，更新成不同于此前的值即可。然后重新触发action。另外可以在action/config/application.json文件中设置formvalidation为false关闭校验，程序不再检查学校是否更新打卡页面。

**Comment by zhiyiYo** [comment]
我用的是 github action，更新了 `AUTOCARD_CACHE_FLAG` 还是不起作用，如果把 `formvalidation` 改为 false 之后提交的表单和后端验证的不一样打卡会成功吗

**Comment by GCS-ZHN** [comment]
> 我用的是 github action，更新了 `AUTOCARD_CACHE_FLAG` 还是不起作用，如果把 `formvalidation` 改为 false 之后提交的表单和后端验证的不一样打卡会成功吗

如果学校的外包开发负责一点做好验证的话，可能可以提示打卡失败而让你知道手动补充打卡。但很多时候新增或修改题目，学校的垃圾外包不会修改其校验规则，导致缺失或漏填打卡结果仍然能提交成功，在辅导员的后台会被发现缺少必填选项。另外我star了您的fork仓库测试一下，您的修改参数是可行的，您可以看看日志提示。或许是因为您选择的时re-run失败的任务而不是重新触发。

**Comment by zhiyiYo** [comment]
> 或许是因为您选择的时re-run失败的任务而不是重新触发。

这个要在哪里设置呢？我应该是没有配置过这个🤔

**Comment by GCS-ZHN** [comment]
> > 或许是因为您选择的时re-run失败的任务而不是重新触发。
> 
> 这个要在哪里设置呢？我应该是没有配置过这个🤔

修改了`AUTOCARD_CACHE_FLAG`后，手动star自己的fork仓库即可测试修改后的效果。无需配置。不要选择重新运行（re-run）之前失败的action workflow。当然您也可以选择修改flag值后什么都不做，第二天再次打卡应当是可行的。

**Comment by zhiyiYo** [comment]
感谢，现在是可以正确提交表单了
