### ISSUE TITLE
功能请求：缓存计划打卡时间和打卡完成情况防止错过打卡

### ISSUE THREAD

**Issue by Mythologyli** [GCS-ZHN/AutoCard#32]
## 异常情况

例如，10 点整打卡任务开始，随机延时 15 分钟后执行打卡上报。如果在这 15 分钟内程序关闭再重新启动，则会错过今日的打卡上报，需要重新更改配置文件调整时间。

## 可能的改进方式

在打卡任务开始时，计算延时并添加一个执行打卡任务。同时，缓存执行打卡时间、是否已执行打卡（假）、打卡用户等必要信息。当执行打卡任务运行后，更新缓存中的是否已执行打卡为真。

如果在等待执行打卡途中发生程序重新启动，若重新启动的时间在执行打卡时间之前，则再次添加任务并等待执行；若重新启动的时间在执行打卡时间之后且未执行打卡，则立即执行打卡。

**Comment by GCS-ZHN** [comment]
邮件已收到，祝您身体健康，工作顺利！
